title: About Git
author: SeulGeek
email: seulgi.choi.mobile@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is site of introduction about Git.
theme: minima

# social links
github_username:  SeulGeek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
